### ISSUE TITLE
No module named scrapy_pagestorage

### ISSUE THREAD

**Issue by Gallaecio** [scrapinghub/scrapinghub-entrypoint-scrapy#54]
In a project using `scrapinghub-entrypoint-scrapy==0.11.0`, I get the following warning:

```
[sh_scrapy.settings] Addon import error scrapy_pagestorage.PageStorageMiddleware:  No module named scrapy_pagestorage
```

Should `scrapy_pagestorage` become a dependency of `scrapinghub-entrypoint-scrapy`? Or should be be disabling the corresponding addon somehow (since we are clearly not using it)?

**Comment by vshlapakov** [comment]
Hey @Gallaecio `scrapinghub-entrypoint-scrapy` doesn't depend on `scrapy_pagestorage` in any sense. What the library actually does - is loading addons enabled in Dash, that's why you see the message. Looks like the addon is built-in and always enabled, which stack are you using? I believe it's the stack that should have `scrapy-pagestorage` on board.

**Comment by Gallaecio** [comment]
We are using a custom Docker image. Should we modify the custom image to install `scrapy-pagestorage`?

**Comment by vshlapakov** [comment]
Installing `scrapy-pagestorage` is the most straightforward way to fix the problem, but I wonder if your custom image is based on some existing stack, or you wrote it by yourself from scratch?

**Comment by Gallaecio** [comment]
The image inherits `FROM python:2.7`, and does nothing fancy. But the source code it copies its dependencies from does not seem to contain "scrapy_pagestorage" or "PageStorageMiddleware" anywhere outside `scrapinghub-entrypoint-scrapy`:

```
(venv) [adrian@pondal veritec-solutions-crawler]$ grep scrapy_pagestorage . -FIR
./venv/lib/python2.7/site-packages/sh_scrapy/settings.py:        "scrapy_pagestorage.PageStorageMiddleware",
(venv) [adrian@pondal veritec-solutions-crawler]$ grep PageStorageMiddleware . -FIR
./venv/lib/python2.7/site-packages/sh_scrapy/settings.py:    "hworker.bot.ext.page.PageStorageMiddleware":
./venv/lib/python2.7/site-packages/sh_scrapy/settings.py:        "scrapy_pagestorage.PageStorageMiddleware",
(venv) [adrian@pondal veritec-solutions-crawler]$ 
```

I checked the project settings in Scrapy Cloud and no trace of those two keywords either.

As for dependencies, we have the following Scrapy-related:
```
scrapy==1.3.3
scrapinghub==2.0.3
scrapinghub-entrypoint-scrapy==0.11.0
scrapy-crawlera==1.2.2
scrapy-splash==0.7
```
And then there is spidermon, installed from an `.egg` on the repository.

I wonder if one of those dependencies may be enabling the add-on.

**Comment by vshlapakov** [comment]
I see, thanks a lot for the details.

> I wonder if one of those dependencies may be enabling the add-on.

None of them, you have to add the dependency by yourself, that's a [separate package](https://github.com/scrapy-plugins/scrapy-pagestorage). Please add it to your requirements.txt (or similar one that you use to add dependencies to the project):
```
scrapy-pagestorage==0.2.2
```

**Comment by Gallaecio** [comment]
Will do, thanks!
