### ISSUE TITLE
scrapy.log has been deprecated in scrapy 1.7

### ISSUE THREAD

**Issue by noviluni** [scrapinghub/scrapinghub-entrypoint-scrapy#56]
`scrapy.log` has been deprecated in scrapy 1.7.0/1.7.1 : https://docs.scrapy.org/en/1.7/news.html .

That makes this package incompatible, as `scrapy.log` is used in `sh_scrapy/log.py`.

**Comment by vshlapakov** [comment]
Addressed by https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy/pull/57, thanks @Milesjpool :+1:
